version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: always
    ports:
      #5672 for ampq
      - "5672:5672"
      #15672 for rabbitmq UI
      - "15672:15672"
    volumes:
      #persistent volume for the queue
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - submit_network

  #submission app container
  submit-app:
    build: ./submit-app
    container_name: submit_app_container
    ports:
      - "3001:3001"
    environment:
      - JOKE_SERVICE_URL=http://10.0.0.4:3000 #change if vm1 ip changes
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - submit_cache:/data/cache #persistent cache
    depends_on:
      - rabbitmq
    networks:
      - submit_network

#private network
networks:
  submit_network:
    driver: bridge

volumes:
  submit_cache: