version: '3.8'

services:
  #submission app container
  submit-app:
    build: ./submit-app
    container_name: submit_app_container
    ports:
      - "3001:3001"
    networks:
      - joke_network

#private network
networks:
  joke_network:
    driver: bridge